In [37]:
# Ignore Warnings.
import warnings
warnings.filterwarnings("ignore")

In [95]:
# Dependencies
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
import datetime as dt
import scipy.stats as st
import re
# Import the data
Hurricane_df = pd.read_csv('Hurricanes/atlantic.csv')
# Hurricane_df.head(10)

# Convert date column as datetime.
Hurricane_df['Date'] = pd.to_datetime(Hurricane_df['Date'] , format= '%Y%m%d')
Hurricane_df.head(5)
# type(Hurricane_df['Maximum Wind'][0])
# print(Hurricane_df)
# Hurricane_df[Hurricane_df<-998] = 0
Hurricane_df = Hurricane_df[['ID', 'Name', 'Date', 'Time', 'Status', 'Latitude', 'Longitude', 'Maximum Wind']]

In [96]:
Hurricane_df.head()

,ID,Name,Date,Time,Status,Latitude,Longitude,Maximum Wind
0,AL011851,UNNAMED,1851-06-25,0,HU,28.0N,94.8W,80
1,AL011851,UNNAMED,1851-06-25,600,HU,28.0N,95.4W,80
2,AL011851,UNNAMED,1851-06-25,1200,HU,28.0N,96.0W,80
3,AL011851,UNNAMED,1851-06-25,1800,HU,28.1N,96.5W,80
4,AL011851,UNNAMED,1851-06-25,2100,HU,28.2N,96.8W,80

In [ ]:
# Create csv file & export data 
city_dataframe.to_csv("new_data.csv")

# Show df
city_dataframe.head(10)

In [80]:
# Convert date column as datetime.
Hurricane_df['Date'] = pd.to_datetime(Hurricane_df['Date'] , format= '%Y%m%d')

# I want to create columns Latitude Hemisphere and Longitude Hemisphere with code 0 = N , 1 = S & 0 = E , 1 = W.
def hemisphere(coord):
        hem = re.findall(r'[NSWE]' , coord)[0]
        if hem == 'N' or hem == 'E':
            return 0
        else:
            return 1

# Creating the column Latitude_Hemisphere.    
Hurricane_df['Latitude_Hemisphere'] = Hurricane_df['Latitude'].apply(hemisphere)
Hurricane_df['Longitude_Hemisphere'] = Hurricane_df['Longitude'].apply(hemisphere)
Hurricane_df['Latitude_Hemisphere'] = Hurricane_df['Latitude_Hemisphere'].astype('category')
Hurricane_df['Longitude_Hemisphere'] = Hurricane_df['Longitude_Hemisphere'].astype('category')

# Convert the latitude and longitude Column to numeric type.
Hurricane_df['Latitude'] =  Hurricane_df['Latitude'].apply(lambda x: re.match('[0-9]{1,3}.[0-9]{0,1}' , x)[0])
Hurricane_df['Longitude'] =   Hurricane_df['Longitude'].apply(lambda x: re.match('[0-9]{1,3}.[0-9]{0,1}' , x)[0])

# The missing values are given by -999. So , we need to fill them appropriately.

# Show the count of missing values and fill them with mean.
for column in Hurricane_df.columns:
    missing_cnt = Hurricane_df[column][Hurricane_df[column] == -999].count()
    print('Missing Values in column {col} = '.format(col = column) , missing_cnt )
    if missing_cnt!= 0:
#         print('in ' , column)
        mean = round(Hurricane_df[column][Hurricane_df[column] != -999 ].mean())
#         print("mean",mean)
        index = Hurricane_df.loc[Hurricane_df[column] == -999 , column].index
#         print("index" , index )
        Hurricane_df.loc[Hurricane_df[column] == -999 , column] = mean
#         print(Hurricane_df.loc[index , column])
        
# Restructure the dataframe for visibility and remove columns ID and Event.        
Hurricane_df =  Hurricane_df[['ID', 'Name', 'Date', 'Time', 'Event', 'Status', 'Latitude', 'Latitude_Hemisphere' , 
       'Longitude', 'Longitude_Hemisphere' ,'Maximum Wind', 'Minimum Pressure', 'Low Wind NE',
       'Low Wind SE', 'Low Wind SW', 'Low Wind NW', 'Moderate Wind NE',
       'Moderate Wind SE', 'Moderate Wind SW', 'Moderate Wind NW',
       'High Wind NE', 'High Wind SE', 'High Wind SW', 'High Wind NW']]

# Change all time to format HHMM.
Hurricane_df['Time'] = Hurricane_df['Time'].astype('object')
def hhmm(time):
    time = str(time)
    digits = re.findall(r'\d', time)
    t = ''
    if len(digits) == 1:
        t ='0{i}00'.format(i =time)
    elif len(digits) == 2:
        t = '{i}00'.format(i =time)
    elif len(digits) == 3:
        t = '0{i}'.format(i =time)
    else:
        t = time
    return t
# Apply the function.
Hurricane_df['Time'] = Hurricane_df['Time'].apply(hhmm)

# Convert the column into Datetime.
Hurricane_df['Time'] = pd.to_datetime(Hurricane_df['Time'] , format='%H%M').dt.time


# Convert the status column to categorical.
Hurricane_df['Status'] = Hurricane_df['Status'].astype('category')

hurricane_data = Hurricane_df.drop(columns = ['ID' , 'Event'])

Missing Values in column ID =  0
Missing Values in column Name =  0
Missing Values in column Date =  0
Missing Values in column Time =  0
Missing Values in column Event =  0
Missing Values in column Status =  0
Missing Values in column Latitude =  0
Missing Values in column Longitude =  0
Missing Values in column Maximum Wind =  0
Missing Values in column Minimum Pressure =  30669
Missing Values in column Low Wind NE =  43184
Missing Values in column Low Wind SE =  43184
Missing Values in column Low Wind SW =  43184
Missing Values in column Low Wind NW =  43184
Missing Values in column Moderate Wind NE =  43184
Missing Values in column Moderate Wind SE =  43184
Missing Values in column Moderate Wind SW =  43184
Missing Values in column Moderate Wind NW =  43184
Missing Values in column High Wind NE =  43184
Missing Values in column High Wind SE =  43184
Missing Values in column High Wind SW =  43184
Missing Values in column High Wind NW =  43184
Missing Values in column Latitude_Hemisphere =  0
Missing Values in column Longitude_Hemisphere =  0

ValueError: unconverted data remains: 0